[33m[nodemon] 3.1.4[39m
[33m[nodemon] to restart at any time, enter `rs`[39m
[33m[nodemon] watching path(s): *.*[39m
[33m[nodemon] watching extensions: js,mjs,cjs,json[39m
[32m[nodemon] starting `node app.js`[39m
node:internal/modules/cjs/loader:998
  throw err;
  ^

Error: Cannot find module '../models/usuario.model'
Require stack:
- C:\Users\User\ApiComida\controllers\usuarios.controller.js
- C:\Users\User\ApiComida\routes\usuarios.routes.js
- C:\Users\User\ApiComida\app.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (C:\Users\User\ApiComida\controllers\usuarios.controller.js:3:17)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\User\\ApiComida\\controllers\\usuarios.controller.js',
    'C:\\Users\\User\\ApiComida\\routes\\usuarios.routes.js',
    'C:\\Users\\User\\ApiComida\\app.js'
  ]
}

Node.js v18.12.0
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node app.js`[39m
C:\Users\User\ApiComida\app.js:31
    console.log(aplicacion corriendo en el puerto ${port})
                ^^^^^^^^^^

SyntaxError: missing ) after argument list
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1088:15)
    at Module._compile (node:internal/modules/cjs/loader:1123:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.12.0
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node app.js`[39m
node:internal/modules/cjs/loader:998
  throw err;
  ^

Error: Cannot find module '../models/usuario.model'
Require stack:
- C:\Users\User\ApiComida\controllers\usuarios.controller.js
- C:\Users\User\ApiComida\routes\usuarios.routes.js
- C:\Users\User\ApiComida\app.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (C:\Users\User\ApiComida\controllers\usuarios.controller.js:3:17)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\User\\ApiComida\\controllers\\usuarios.controller.js',
    'C:\\Users\\User\\ApiComida\\routes\\usuarios.routes.js',
    'C:\\Users\\User\\ApiComida\\app.js'
  ]
}

Node.js v18.12.0
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node app.js`[39m
C:\Users\User\ApiComida\app.js:31
    console.log(aplicacion corriendo en el puerto ${port})
                ^^^^^^^^^^

SyntaxError: missing ) after argument list
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1088:15)
    at Module._compile (node:internal/modules/cjs/loader:1123:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.12.0
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node app.js`[39m
C:\Users\User\ApiComida\app.js:31
    console.log(aplicacion corriendo en el puerto ${port})
                ^^^^^^^^^^

SyntaxError: missing ) after argument list
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1088:15)
    at Module._compile (node:internal/modules/cjs/loader:1123:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.12.0
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node app.js`[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node app.js`[39m
[32m[nodemon] restarting due to changes...[39m
node:internal/modules/cjs/loader:998
  throw err;
  ^

Error: Cannot find module '../models/usuario.model'
Require stack:
- C:\Users\User\ApiComida\controllers\usuarios.controller.js
- C:\Users\User\ApiComida\routes\usuarios.routes.js
- C:\Users\User\ApiComida\app.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (C:\Users\User\ApiComida\controllers\usuarios.controller.js:3:17)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\User\\ApiComida\\controllers\\usuarios.controller.js',
    'C:\\Users\\User\\ApiComida\\routes\\usuarios.routes.js',
    'C:\\Users\\User\\ApiComida\\app.js'
  ]
}

Node.js v18.12.0
[32m[nodemon] starting `node app.js`[39m
node:internal/modules/cjs/loader:998
  throw err;
  ^

Error: Cannot find module '../models/usuario.model'
Require stack:
- C:\Users\User\ApiComida\controllers\usuarios.controller.js
- C:\Users\User\ApiComida\routes\usuarios.routes.js
- C:\Users\User\ApiComida\app.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (C:\Users\User\ApiComida\controllers\usuarios.controller.js:3:17)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\User\\ApiComida\\controllers\\usuarios.controller.js',
    'C:\\Users\\User\\ApiComida\\routes\\usuarios.routes.js',
    'C:\\Users\\User\\ApiComida\\app.js'
  ]
}

Node.js v18.12.0
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node app.js`[39m
aplicacion corriendo en el puerto 4000
Conectado a mongo db
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node app.js`[39m
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::4000
    at Server.setupListenHandle [as _listen2] (node:net:1485:16)
    at listenInCluster (node:net:1533:12)
    at Server.listen (node:net:1621:7)
    at Function.listen (C:\Users\User\ApiComida\node_modules\express\lib\application.js:635:24)
    at Object.<anonymous> (C:\Users\User\ApiComida\app.js:30:5)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1512:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '::',
  port: 4000
}

Node.js v18.12.0
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node app.js`[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node app.js`[39m
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::4000
    at Server.setupListenHandle [as _listen2] (node:net:1485:16)
    at listenInCluster (node:net:1533:12)
    at Server.listen (node:net:1621:7)
    at Function.listen (C:\Users\User\ApiComida\node_modules\express\lib\application.js:635:24)
    at Object.<anonymous> (C:\Users\User\ApiComida\app.js:30:5)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1512:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '::',
  port: 4000
}

Node.js v18.12.0
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node app.js`[39m
node:internal/modules/cjs/loader:998
  throw err;
  ^

Error: Cannot find module '../models/usuario.model'
Require stack:
- C:\Users\User\ApiComida\controllers\usuarios.controller.js
- C:\Users\User\ApiComida\routes\usuarios.routes.js
- C:\Users\User\ApiComida\app.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (C:\Users\User\ApiComida\controllers\usuarios.controller.js:3:17)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\User\\ApiComida\\controllers\\usuarios.controller.js',
    'C:\\Users\\User\\ApiComida\\routes\\usuarios.routes.js',
    'C:\\Users\\User\\ApiComida\\app.js'
  ]
}

Node.js v18.12.0
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node app.js`[39m
node:internal/modules/cjs/loader:998
  throw err;
  ^

Error: Cannot find module '../models/usuario.model'
Require stack:
- C:\Users\User\ApiComida\controllers\usuarios.controller.js
- C:\Users\User\ApiComida\routes\usuarios.routes.js
- C:\Users\User\ApiComida\app.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (C:\Users\User\ApiComida\controllers\usuarios.controller.js:3:17)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\User\\ApiComida\\controllers\\usuarios.controller.js',
    'C:\\Users\\User\\ApiComida\\routes\\usuarios.routes.js',
    'C:\\Users\\User\\ApiComida\\app.js'
  ]
}

Node.js v18.12.0
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting due to changes...[39m
[32m[nodemon] starting `node app.js`[39m
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::4000
    at Server.setupListenHandle [as _listen2] (node:net:1485:16)
    at listenInCluster (node:net:1533:12)
    at Server.listen (node:net:1621:7)
    at Function.listen (C:\Users\User\ApiComida\node_modules\express\lib\application.js:635:24)
    at Object.<anonymous> (C:\Users\User\ApiComida\app.js:31:5)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1512:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '::',
  port: 4000
}

Node.js v18.12.0
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
[32m[nodemon] restarting child process[39m
[32m[nodemon] starting `node app.js`[39m
aplicacion corriendo en el puerto 4000
Conectado a mongo db
^C